name: CI for React App

on:
  push:
    branches:
      - main # Ejecutar el flujo de trabajo cuando se haga push a la rama principal
  pull_request:
    branches:
      - main # Ejecutar el flujo de trabajo cuando se abra un pull request hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest # Usar una máquina virtual Ubuntu
    environment: Prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Descargar el código fuente del repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2 # Configurar Node.js
        with:
          node-version: "20" # Puedes ajustar la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install # Instalar las dependencias de tu proyecto React

      - name: 📝 Create .env file for Vite
        run: |
          echo "VITE_API_URL_CLIENTS=${{ secrets.VITE_API_URL_CLIENTS }}" >> .env
          echo "VITE_API_URL_SELLERS=${{ secrets.VITE_API_URL_SELLERS }}" >> .env
          echo "VITE_API_URL_WAREHOUSE=${{ secrets.VITE_API_URL_WAREHOUSE }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_NODE_ENV=${{ secrets.VITE_NODE_ENV }}" >> .env
          echo "VITE_PORT=${{ secrets.VITE_PORT }}" >> .env
          echo "VITE_API_REACT_APP_GOOGLE_MAPS_API_KEY=${{secrets.VITE_API_REACT_APP_GOOGLE_MAPS_API_KEY}}" >> .env

      - name: 📝 Show .env file (for debug only)
        run: cat .env

      - name: Run tests
        run: npm test -- --coverage # Ejecutar las pruebas y generar el reporte de cobertura
